### ISSUE TITLE
Unable to open project

### ISSUE THREAD

**Issue by BergenCalling** [StoXProject/RstoxFDA#95]
I made some changes to my project (spatial distribution) and now I cannot longer open the project (I am still able to open my other projects in Stox). Error message: > The file C:/Users/siljes/workspace/stox/project/ECA_CC_NEA_2022/process/project.json is not a valid project.json file. Run the following code in R to see the JSON schema validation error: err <- readRDS("C:\Users\siljes\AppData\Local\Temp\Rtmp08mAbL/projectJSONValidatorError.rds")

**Comment by edvinf** [comment]
This is probably related to the bug describd in https://github.com/StoXProject/RstoxFDA/issues/90. Fixing that issue is a high priority, but meanwhile a workaround may be to edit the project.json file in a plain-text editor and replace all occurrences of "CarValue" with "CarValues".

If you want some confirmation that the issue is the same as #90 before testing the workaround, you can upload the projectJSONValidatorError.rds to this issue.

**Comment by BergenCalling** [comment]
I changed all the occurences of "CarValue" with "CarValues", but now I got this error message: Unable to parse the StoX description file C:/Users/siljes/workspace/stox/project/ECA_CC_NEA_2022/process/project.json, as jsonlite::read_json reported the error Error in parse_con(txt, bigint_as_char): lexical error: invalid char in json text. icialRstoxFrameworkVersion": CarValues, "DependentP (right here) ------^

**Comment by edvinf** [comment]
I have noted that this issue is fixed. Feel free to re-open the issue if not.
