### ISSUE TITLE
ReportFDASampling: Sampling of fisheries changes with number of grouping variables

### ISSUE THREAD

**Issue by BergenCalling** [StoXProject/RstoxFDA#97]
Number of vessels and catches increases with increasing number of GroupingVariables. LengthMeasurments and AgeReadings are constant

**Comment by edvinf** [comment]
This behaviour is expected for vessels, but not for catches.

ReportFDASampling tabulates the number of unique vessels sampled in each cell (combination of grouping variables). When more grouping variables are introduced, the same vessel may be counted several times between the different cells. E.g. The same vessel may be sampled in several Quarters, and be counted several times when Quarter is introduced as a grouping variable.

In principle, the same may apply to catches, of for instance Usage is used as a grouping variable.  The same catch may be fated for both human consumption and industrial usage. But for the common grouping variables, the total sum of catches should be invariant. This happens because the current RstoxFDA implementation counts the number of unique StoxBiotic-Stations as the number of catches. It should rather count the number of hauls.

In order to make sure that there is not something more going on, it would be nice if you could confirm that your project contains some hauls that are attributed to the same station (look for warnings like this in baseline: 'There are more than one 'serialnumber' (HaulKey in StoxBioticData) for x out of y 'station'(StationKey in StoxBioticData) in the NMDBiotic data'), or that you are not using 'Usage' or any added column as grouping variable.

I consider this a bug, since catch should be identified with haul, rather than station, and will change the implementation. I will also try to clarify the documentation a bit, making explcit that unique catches and vessels are counted, and rephrase the text about SamplingVariables so that the situation with double counting does not appear to only happen when SamplingVariables are added.

**Comment by BergenCalling** [comment]
I confirm that my project contains some hauls that are attributed to the same station
